### ISSUE TITLE
Deploy GraphQL API

### ISSUE THREAD

**Issue by colebemis** [primer/api#1]
Let's deploy the Primer GraphQL API so people can use it. 

**Notes**
* We should automatically deploy the API to production when new commits are pushed to `main`
* It would be nice if we could deploy it to `https://primer.style/api`
* When you visit `https://primer.style/api` in a browser, it should render an interactive GraphQL API playground

**Comment by potatoqualitee** [comment]
Yes please!! I'm desperate for this.
